[package]
name = "s739"
version = "0.2.2"
edition = "2021"
authors = ["vvh413"]
description = "Steganography tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
bitvec = "1.0.1"
clap = { version = "4.3.17", features = ["derive"] }
image = "0.24.6"
